INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('afghanistan', 'afganistán', 'af', '004')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('aland islands', 'islas de åland', 'ax', '248')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('albania', 'albania', 'al', '008')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('algeria', 'argelia', 'dz', '012')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('american samoa', 'samoa americana', 'as', '016')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('andorra', 'andorra', 'ad', '020')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('angola', 'angola', 'ao', '024')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('anguilla', 'anguila', 'ai', '660')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('antigua and barbuda', 'antigua & barbuda', 'ag', '028')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('argentina', 'argentina', 'ar', '032')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('armenia', 'armenia', 'am', '051')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('aruba', 'aruba', 'aw', '533')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('australia', 'australia', 'au', '036')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('austria', 'austria', 'at', '040')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('azerbaijan', 'azerbaiyán', 'az', '031')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bahamas, the', 'las bahamas', 'bs', '044')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bahrain', 'barein', 'bh', '048')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bangladesh', 'bangladesh', 'bd', '050')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('barbados', 'barbados', 'bb', '052')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('belarus', 'bielorrusia', 'by', '112')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('belgium', 'bélgica', 'be', '056')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('belize', 'belice', 'bz', '084')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('benin', 'benin', 'bj', '204')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bermuda', 'bermuda', 'bm', '060')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bhutan', 'bután', 'bt', '064')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bolivia', 'bolivia', 'bo', '068')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bosnia and herzegovina', 'bosnia', 'ba', '070')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('botswana', 'botsuana', 'bw', '072')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bouvet island', 'isla bouvet', 'bv', '074')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('br indian ocean terr', 'territorio británico oce. indico', 'io', '086')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('brazil', 'brasil', 'br', '076')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('british virgin is.', 'islas vírgenes británicas', 'vg', '092')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('brunei', 'brunei', 'bn', '096')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('bulgaria', 'bulgaria', 'bg', '100')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('burkina', 'burkina', 'bf', '854')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('burma', 'burma', 'mm', '104')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('burundi', 'burundi', 'bi', '108')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cambodia', 'camboya', 'kh', '116')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cameroon', 'camerún', 'cm', '120')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('canada', 'canadá', 'ca', '124')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cape verde', 'cabo verde', 'cv', '132')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cayman islands', 'islas caimán', 'ky', '136')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('central african rep.', 'república centroafricana', 'cf', '140')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('chad', 'chad', 'td', '148')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('chile', 'chile', 'cl', '152')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('china', 'china', 'cn', '156')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('christmas island', 'isla de navidad', 'cx', '162')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cocos (keeling) islands', 'islas cocos', 'cc', '166')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('colombia', 'colombia', 'co', '170')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('comoros', 'comoros', 'km', '174')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('congo', 'congo', 'cd', '178')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('congo, democratic republic of the', 'república democrática del congo', 'cg', '180')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cook islands', 'islas cook', 'ck', '184')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('costa rica', 'costa rica', 'cr', '188')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cote d'ivoire', 'costa de marfil', 'ci', '384')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('croatia', 'croacia', 'hr', '191')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cuba', 'cuba', 'cu', '192')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('cyprus', 'chipre', 'cy', '196')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('czech republic', 'república checa', 'cz', '203')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('denmark', 'dinamarca', 'dk', '208')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('dijibouti', 'yibuti', 'dj', '262')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('dominica', 'dominica', 'dm', '212')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('dominican republic', 'república dominicana', 'do', '214')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('ecuador', 'ecuador', 'ec', '218')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('egypt', 'egipto', 'eg', '818')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('el salvador', 'el salvador', 'sv', '222')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('equatorial guinea', 'guinea ecuatorial', 'gq', '226')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('eritrea', 'eritrea', 'er', '232')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('estonia', 'estonia', 'ee', '233')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('ethiopia', 'etiopía', 'et', '231')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('falkland (is malvinas)', 'islas malvinas', 'fk', '238')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('faroe islands', 'islas faroe', 'fo', '234')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('fed states micronesia', 'estados federados de micronesia', 'fm', '583')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('fiji', 'fiji', 'fj', '242')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('finland', 'finlandia', 'fi', '246')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('french territories', 'territorios franceses', 'tf', '260')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('france', 'francia', 'fr', '250')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('french guiana', 'guyana francesa', 'gf', '254')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('french polynesia', 'polinesia francesa', 'pf', '258')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('gabon', 'gabón', 'ga', '266')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('gambia, the', 'gambia', 'gm', '270')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('georgia', 'georgia', 'ge', '268')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('germany', 'alemania', 'de', '276')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('ghana', 'ghana', 'gh', '288')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('gibraltar', 'gibraltar', 'gi', '292')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('greece', 'grecia', 'gr', '300')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('greenland', 'groenlandia', 'gl', '304')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('grenada', 'granada', 'gd', '308')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guadeloupe', 'guadalupe', 'gp', '312')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guam', 'guam', 'gu', '316')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guatemala', 'guatemala', 'gt', '320')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guinea', 'guinea', 'gn', '324')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guinea-bissau', 'guinea-bissau', 'gw', '624')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('guyana', 'guyana', 'gy', '328')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('haiti', 'haití', 'ht', '332')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('heard is&mcdonald isls', 'islas heard y mcdonald', 'hm', '334')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('honduras', 'honduras', 'hn', '340')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('hong kong', 'hong kong', 'hk', '344')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('hungary', 'hungría', 'hu', '348')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('iceland', 'islandia', 'is', '352')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('india', 'india', 'in', '356')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('indonesia', 'indonesia', 'id', '360')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('iran', 'irán', 'ir', '364')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('iraq', 'irak', 'iq', '368')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('ireland', 'irlanda', 'ie', '372')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('israel', 'israel', 'il', '376')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('italy', 'italia', 'it', '380')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('jamaica', 'jamaica', 'jm', '388')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('japan', 'japón', 'jp', '392')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('jordan', 'jordania', 'jo', '400')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('kazakhstan', 'kazajistán', 'kz', '398')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('kenya', 'kenia', 'ke', '404')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('kiribati', 'kiribati', 'ki', '296')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('korea, republic of', 'corea del sur', 'kr', '410')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('korea,dem peoples rep', 'corea del norte', 'kp', '408')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('kuwait', 'kuwait', 'kw', '414')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('kyrgyzstan', 'kirguistán', 'kg', '417')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('laos', 'laos', 'la', '418')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('latvia', 'letonia', 'lv', '428')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('lebanon', 'líbano', 'lb', '422')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('lesotho', 'lesoto', 'ls', '426')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('liberia', 'liberia', 'lr', '430')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('libya', 'libia', 'ly', '434')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('liechtenstein', 'liechtenstein', 'li', '438')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('lithuania', 'lituania', 'lt', '440')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('luxembourg', 'luxemburgo', 'lu', '442')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('macau', 'macao', 'mo', '446')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('macedonia', 'macedonia', 'mk', '807')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('madagascar', 'madagascar', 'mg', '450')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('malawi', 'malawi', 'mw', '454')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('malaysia', 'malasia', 'my', '458')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('maldives', 'maldivas', 'mv', '462')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mali', 'mali', 'ml', '466')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('malta', 'malta', 'mt', '470')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('marshall islands', 'islas marshall', 'mh', '584')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('martinique', 'martinica', 'mq', '474')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mauritania', 'mauritania', 'mr', '478')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mauritius', 'mauricio', 'mu', '480')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mayotte', 'mayotte', 'yt', '175')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mexico', 'méxico', 'mx', '484')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('moldova', 'moldavia', 'md', '498')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('monaco', 'mónaco', 'mc', '492')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mongolia', 'mongolia', 'mn', '496')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('montenegro', 'montenegro', 'me', '499')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('montserrat', 'montserrat', 'ms', '500')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('morocco', 'marruecos', 'ma', '504')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('mozambique', 'mozambique', 'mz', '508')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('namibia', 'namibia', 'na', '516')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('nauru', 'nauru', 'nr', '520')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('nepal', 'nepal', 'np', '524')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('netherlands', 'holanda', 'nl', '528')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('netherlands antilles', 'antillas holandesas', 'an', '530')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('new caledonia', 'nueva caledonia', 'nc', '540')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('new zealand', 'nueva zelandia', 'nz', '554')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('nicaragua', 'nicaragua', 'ni', '558')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('niger', 'níger', 'ne', '562')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('nigeria', 'nigeria', 'ng', '566')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('niue', 'niue', 'nu', '570')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('norfolk island', 'isla norfolk', 'nf', '574')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('northern mariana is', 'islas marianas del norte', 'mp', '580')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('norway', 'noruega', 'no', '578')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('oman', 'omán', 'mu', '512')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('pakistan', 'pakistán', 'pk', '586')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('panama', 'panamá', 'pa', '591')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('papua new guinea', 'papua nueva guinea', 'pg', '598')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('paraguay', 'paraguay', 'py', '600')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('palau republic of', 'palaos', 'pw', '275')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('peru', 'perú', 'pe', '604')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('philippines', 'filipinas', 'ph', '608')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('pitcairn islands', 'islas pitcáirn', 'pn', '612')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('poland', 'polonia', 'pl', '616')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('portugal', 'portugal', 'pt', '620')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('puerto rico', 'puerto rico', 'pr', '630')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('qatar', 'catar', 'qa', '634')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('reunion', 'reunión', 're', '638')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('romania', 'rumania', 'ro', '642')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('russia', 'rusia', 'rs', '643')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('rwanda', 'ruanda', 'rw', '646')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('san marino', 'san marino', 'sm', '674')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('sao tome and principe', 'santo tomé y principe', 'st', '678')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('saudi arabia', 'arabia saudita', 'sa', '682')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('senegal', 'senegal', 'sn', '686')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('serbia', 'serbia', 'cs', '688')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('seychelles', 'seychelles', 'sc', '690')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('sierra leone', 'sierra leona', 'sl', '694')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('singapore', 'singapur', 'sg', '702')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('slovakia', 'eslovaquia', 'sk', '703')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('slovenia', 'eslovenia', 'si', '705')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('solomon islands', 'islas salomón', 'sb', '090')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('somalia', 'somalia', 'so', '706')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('south africa', 'sudáfica', 'za', '710')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('spain', 'españa', 'es', '724')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('sri lanka', 'sri lanka', 'lk', '144')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('st lucia', 'santa lucía', 'lc', '662')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('st. helena', 'isla santa elena', 'sh', '654')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('st. kitts and nevis', 'san cristóbal y nieves', 'kn', '659')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('st. pierre and miquelon', 'san pedro y miguelón', 'sb', '666')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('st. vincent/grenadines', 'san vicente y las granadinas', 'vc', '670')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('sudan', 'sudán', 'sd', '736')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('suriName', 'surinam', 'sr', '740')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('swaziland', 'suazilandia', 'sz', '748')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('sweden', 'suecia', 'se', '752')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('switzerland', 'suiza', 'ch', '756')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('syria', 'siria', 'sy', '760')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('taiwan', 'taiwán', 'tw', '158')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tajikistan', 'tajikistán', 'tj', '762')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tanzania, united rep of', 'tanzania', 'tz', '834')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('thailand', 'tailandia', 'th', '764')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('timor-leste', 'timor oriental', 'tl', '626')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('togo', 'togo', 'tg', '768')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tokelau', 'tokelau', 'tk', '772')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tonga', 'tonga', 'to', '776')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('trinidad & tobago', 'trinidad y tobago', 'tt', '780')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tunisia', 'túnez', 'tn', '788')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('turkey', 'turquía', 'tr', '792')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('turkmenistan', 'turkmenistán', 'tm', '795')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('turks and caicos isl', 'islas turcas y caicos', 'tc', '796')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('tuvalu', 'tuvalu', 'tv', '798')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('uganda', 'uganda', 'ug', '800')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('ukraine', 'ucraina', 'ua', '804')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('united arab emirates', 'emiratos árabes unidos', 'ae', '784')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('united kingdom', 'reino unido', 'gb', '826')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('united states', 'estados unidos', 'us', '840')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('uruguay', 'uruguay', 'uy', '858')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('uzbekistan', 'uzbekistán', 'uz', '860')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('vanuatu', 'vanuatu', 'vu', '548')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('vatican city', 'ciudad del vaticano', 'va', '336')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('venezuela', 'venezuela', 've', '862')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('vietnam', 'vietnam', 'vn', '704')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('virgin islands', 'islas vírgenes', 'vi', '850')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('wallis and futuna', 'wallis y futuna', 'wf', '876')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('western sahara', 'sahara occidental', 'eh', '732')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('western samoa', 'samoa occidental', 'ws', '882')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('yemen', 'yemén', 'ye', '887')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('zambia', 'zambia', 'za', '894')
INSERT INTO Countries (Name, SpanishName, ShortName, Id) VALUES ('zimbabwe', 'zimbabue', 'zw', '716')